#!/usr/bin/env python3
"""
python_adapter.py — Python 语言适配器。

识别范围：def / async def / class（含装饰器紧跟的定义）。

相比早期版本的已知修正：
- 只在 class 内部递归查找嵌套方法，不递归进普通函数体内部找嵌套函数
  （对齐真实 tree-sitter 版 repomap 的行为，这是用真实项目对比实测确认的差异，
  见 references/known_limitations.md）。函数体内部的嵌套定义（比如测试代码里
  `def test_x(): def inner(): ...` 这种模式）不会被当作独立符号收录。

新增 `is_generated()`：识别 protobuf/gRPC 生成代码的标记注释（`# Generated
by the protocol buffer compiler.  DO NOT EDIT!`、`# Generated by the gRPC
Python protocol compiler plugin. DO NOT EDIT!`）。用真实
`python -m grpc_tools.protoc` 生成的 `*_pb2.py`/`*_pb2_grpc.py` 文件验证过
——不过滤的话，gRPC 生成的 stub 类（`FooStub`/`FooServicer`）会完整出现在
地图里，纯粹是样板代码，对理解项目实际写了什么没有价值。
"""

from __future__ import annotations

import re
from pathlib import Path

from adapter_base import AdapterResult, Symbol, register
from adapter_utils import indent_of, matches_generated_file_markers, skip_python_style_triple_quoted_strings

PY_DEF_RE = re.compile(r"^(\s*)(async\s+def|def|class)\s+([A-Za-z_][A-Za-z0-9_]*)")
PY_DECORATOR_RE = re.compile(r"^(\s*)@[A-Za-z_][A-Za-z0-9_.]*")

# protobuf/gRPC 生成的 Python 文件用的两种官方标记文案（分别对应 protoc 的
# Python 插件和 gRPC 的 Python 插件，两者文案不完全一样，都要覆盖）。
_GENERATED_MARKERS = (
    re.compile(r"^\s*#\s*Generated by the protocol buffer compiler\.\s*DO NOT EDIT!\s*$"),
    re.compile(r"^\s*#\s*Generated by the gRPC Python protocol compiler plugin\. DO NOT EDIT!\s*$"),
)


class PythonAdapter:
    name = "python"

    def match(self, filepath) -> bool:
        return Path(filepath).suffix == ".py"

    def is_generated(self, lines: list[str]) -> bool:
        return matches_generated_file_markers(lines, _GENERATED_MARKERS)

    def extract_symbols(self, filepath, lines: list[str]) -> AdapterResult:
        symbols: list[Symbol] = []
        in_triple = skip_python_style_triple_quoted_strings(lines)

        # class_stack 记录当前"仍然对嵌套收录开放"的 class 缩进层级。
        # 规则：只有当一个新定义的缩进恰好比某个仍在栈顶的 class 深一级时，
        # 才把它当作该 class 的方法（depth = class的depth + 1）；
        # 如果新定义缩进比栈顶的 class 更深两级以上（说明是方法体内部的嵌套函数），
        # 或者压根不在任何 class 之内，一律按 depth=0（不收录为嵌套）。
        # 这样能对齐"只在class内递归找方法，不递归进函数体"的真实基准行为。
        class_stack: list[tuple[int, int]] = []  # (class自身的indent, class的depth)

        n = len(lines)
        i = 0
        while i < n:
            if in_triple[i]:
                i += 1
                continue

            raw = lines[i]
            stripped = raw.rstrip("\n")

            if PY_DECORATOR_RE.match(stripped):
                i += 1
                continue

            m = PY_DEF_RE.match(stripped)
            if not m:
                i += 1
                continue

            indent = indent_of(stripped)
            keyword = m.group(2)

            # 弹出所有缩进 >= 当前行的 class（说明已经离开了那个 class 的作用域）
            while class_stack and class_stack[-1][0] >= indent:
                class_stack.pop()

            if class_stack and indent == class_stack[-1][0] + 4:
                # 恰好是栈顶 class 的直接子层级 -> 是这个 class 的方法
                depth = class_stack[-1][1] + 1
            elif not class_stack:
                # 不在任何 class 内部，且缩进为0 -> 顶层定义
                # （如果缩进>0但不在class内，说明是某个函数体内部的嵌套定义，
                # 按真实基准行为不收录为嵌套符号，也不视为顶层，直接跳过）
                if indent == 0:
                    depth = 0
                else:
                    i += 1
                    continue
            else:
                # 在某个 class 内部，但缩进比"方法应有的缩进"更深
                # -> 是某个方法体内部的嵌套定义，不收录
                i += 1
                continue

            if keyword == "class":
                class_stack.append((indent, depth))

            # 抓取紧随其后的单行 docstring
            doc = None
            if i + 1 < n:
                nxt = lines[i + 1].strip()
                dm = re.match(r'^("""(.*?)"""|\'\'\'(.*?)\'\'\')\s*$', nxt)
                if dm:
                    doc = (dm.group(2) or dm.group(3) or "").strip()

            symbols.append(Symbol(name=stripped.strip(), depth=depth, docstring=doc, line_no=i + 1))
            i += 1

        return AdapterResult(symbols=symbols)


register(PythonAdapter())
