#!/usr/bin/env python3
"""
adapter_base.py — 语言适配器的核心接口定义。

设计目标：新增一种语言/技术栈的支持，只需要新写一个适配器类并在
adapters/__init__.py 里注册，不需要改动 repomap_lite.py 的核心调度逻辑、
CLI、增量更新、渲染格式等任何一处。

每个适配器负责回答两个问题：
1. 这个文件我认不认？(match_extensions / match_filename)
2. 认的话，从文件内容里抠出哪些符号，以及它们的嵌套层级？(extract_symbols)

适配器之间互不感知，互不依赖，可以独立增删。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Protocol


@dataclass
class Symbol:
    """一个被识别出的符号（函数/类/结构体/接口等定义）"""
    name: str                          # 展示用的完整定义行文本（已 strip，不含前导缩进）
    depth: int                         # 嵌套深度，0 = 顶层
    docstring: str | None = None       # 单行 docstring/注释摘要（可选，不是所有语言都有）
    line_no: int = 0                   # 源文件行号（1-indexed），便于溯源


@dataclass
class AdapterResult:
    """一个适配器处理完一个文件后的结果"""
    symbols: list[Symbol] = field(default_factory=list)
    # 适配器可以在这里报告"部分支持"的情况，例如 Vue 文件只解析了 <script> 块，
    # 或者某种语法结构遇到了已知不支持的特殊写法。用于诊断，不影响输出格式。
    notes: list[str] = field(default_factory=list)


class LanguageAdapter(Protocol):
    """
    所有语言适配器必须实现这个接口。

    用 Protocol 而不是抽象基类，是为了让适配器可以是简单的模块级函数集合
    （不强制用类），降低新增适配器的门槛——一个新语言的适配器可以只是
    一个几十行的文件，只要实现这三个东西。
    """

    # 适配器的唯一标识，用于日志/诊断信息和来源标记
    name: str

    def match(self, filepath) -> bool:
        """判断这个适配器是否应该处理该文件（通常按扩展名判断，
        但也可以按文件名本身判断，例如 CMakeLists.txt 这类无扩展名文件）。
        """
        ...

    def extract_symbols(self, filepath, lines: list[str]) -> AdapterResult:
        """
        从文件的行列表中抽取符号。lines 保留原始的行结尾（keepends=True 读入），
        方便适配器自己处理跨行结构（多行字符串、多行签名等）。

        filepath 一并传入，是因为部分适配器需要按路径判断方言/子模式
        （例如 shader 适配器要靠扩展名区分 GLSL/HLSL/WGSL 三种完全不同的语法规则）。
        大多数适配器可以忽略这个参数，只有 match() 里已经用到扩展名的适配器
        通常也就够用了；只有像 shader 这种"一个适配器覆盖多种方言"的情况才需要
        在 extract_symbols 内部再次读取它。

        返回的 Symbol.depth 从 0 开始，同一文件内的嵌套关系必须自洽
        （即：所有 depth=0 的符号是顶层，depth=1 的必须能追溯到某个更早出现的
        depth=0 符号作为"父级"，渲染时按 depth 直接乘以缩进宽度）。
        """
        ...

    def is_generated(self, lines: list[str]) -> bool:
        """
        判断这个文件是不是"自动生成、不该被当作手写项目代码看待"的文件——
        比如 Go 的 protobuf/gRPC/mock 生成代码（标记
        `// Code generated ... DO NOT EDIT.`）、Python 的 protobuf 生成代码
        （标记 `# Generated by the protocol buffer compiler.  DO NOT EDIT!`）。

        这是一个**可选**方法，默认实现（见 adapter_base.py 里的
        `default_is_generated`）返回 False（不认为是生成文件），已有的
        适配器完全不需要改动就能继续工作——只有语言本身有明确的、广泛使用
        的生成文件标记约定时，才值得在对应适配器里覆盖这个方法。

        设计成"每个适配器自己判断"而不是在 repomap_lite.py 核心调度层
        维护一份跨语言的正则列表，原因跟整个适配器架构的设计初衷一致：
        "文件里的什么样内容算作生成代码"是语言/生态相关的知识（Go 的标记
        格式和 Python 的标记格式完全不同，Java 用的是 `@Generated` 注解
        而不是注释行），把这部分知识塞进一个跟具体语言无关的全局列表，
        新增一种语言的生成文件识别就必须去改核心调度代码——这正是适配器
        架构从一开始就要避免的耦合。新增一种语言的生成文件识别，只需要
        在对应的适配器里覆盖 `is_generated`，不需要碰 repomap_lite.py。

        典型实现只需要检查文件开头几行是否匹配已知标记（真实生成器的
        约定基本都要求标记出现在文件最开头），不需要全文扫描。
        """
        ...


# ---------------------------------------------------------------------------
# 适配器注册表
# ---------------------------------------------------------------------------
# 新增语言支持的唯一步骤：
#   1. 在 adapters/ 目录下新建一个文件，例如 adapters/rust_adapter.py
#   2. 在该文件里实现一个满足 LanguageAdapter 接口的对象
#   3. 在 adapters/__init__.py 的 ALL_ADAPTERS 列表里加入这个对象
# 不需要改动 repomap_lite.py 的任何一行。

_REGISTRY: list[LanguageAdapter] = []


def register(adapter: LanguageAdapter) -> LanguageAdapter:
    """装饰器/函数：把一个适配器实例加入全局注册表。"""
    _REGISTRY.append(adapter)
    return adapter


def all_adapters() -> list[LanguageAdapter]:
    return list(_REGISTRY)


def find_adapter_for(filepath) -> LanguageAdapter | None:
    """按注册顺序找第一个 match() 返回 True 的适配器。
    注册顺序在 adapters/__init__.py 中定义，更"专用"的适配器
    （例如 Vue 单文件组件）应该排在更"通用"的适配器（例如纯 JS）之前，
    因为 .vue 文件本质也可能被通用规则误判。
    """
    for adapter in _REGISTRY:
        if adapter.match(filepath):
            return adapter
    return None


def adapter_says_generated(adapter: LanguageAdapter, lines: list[str]) -> bool:
    """
    安全地调用 adapter.is_generated(lines)，兼容"这个适配器根本没实现
    is_generated"的情况（`LanguageAdapter` 是 `Protocol`，不强制适配器
    真的定义这个方法；早期写的适配器不需要为了这一个新增的可选能力去
    改动自己的代码）。没实现就当作"不是生成文件"处理，这是最安全的默认值
    ——宁可不小心把一个真实生成文件当作手写代码展示（多展示了一些噪音），
    也不要反过来把一个适配器没预料到的"实现了 is_generated 但因为某种
    原因抛异常"的情况当成了"是生成文件"从而丢失真实内容。
    """
    method = getattr(adapter, "is_generated", None)
    if method is None:
        return False
    try:
        return bool(method(lines))
    except Exception:  # noqa: BLE001 — 单个适配器的可选能力出错不该影响主流程
        return False
